insert into `products_category` (`id`, `title`) values (1, 'Apparel');
insert into `products_category` (`id`, `title`) values (2, 'Cuidado Personal');
insert into `products_category` (`id`, `title`) values (3, 'Drinkware');
insert into `products_category` (`id`, `title`) values (4, 'Eco Friendly');
insert into `products_category` (`id`, `title`) values (5, 'Eco Friendly');
insert into `products_category` (`id`, `title`) values (6, 'Escritura');
insert into `products_category` (`id`, `title`) values (7, 'Golf');
insert into `products_category` (`id`, `title`) values (8, 'Gorras');
insert into `products_category` (`id`, `title`) values (9, 'Herramientas');
insert into `products_category` (`id`, `title`) values (10, 'Hogar');
insert into `products_category` (`id`, `title`) values (11, 'Identificadores');
insert into `products_category` (`id`, `title`) values (12, 'Juegos');
insert into `products_category` (`id`, `title`) values (13, 'Llaveros');
insert into `products_category` (`id`, `title`) values (14, 'Marcas');
insert into `products_category` (`id`, `title`) values (15, 'Marroquinería');
insert into `products_category` (`id`, `title`) values (16, 'Mates y Accesorios');
insert into `products_category` (`id`, `title`) values (17, 'Mix Stuff');
insert into `products_category` (`id`, `title`) values (18, 'Novedades');
insert into `products_category` (`id`, `title`) values (19, 'Oficina');
insert into `products_category` (`id`, `title`) values (20, 'Outdoor');
insert into `products_category` (`id`, `title`) values (21, 'Paraguas');
insert into `products_category` (`id`, `title`) values (22, 'POP - Punto de Venta');
insert into `products_category` (`id`, `title`) values (23, 'Productos Destacados');
insert into `products_category` (`id`, `title`) values (24, 'Relojes');
insert into `products_category` (`id`, `title`) values (25, 'Sin Categoría');
insert into `products_category` (`id`, `title`) values (26, 'Tecnología');
